x_size = 14
y_size = 10
num_agents = 2
num_agents_must_finish = 2

[victory_conditions]
BlocksSatisfied = 2

#   0123456789ABCD
# 0           G## 
# 1               
# 2               
# 3 ##            
# 4         G     
# 5            ## 
# 6               
# 7 ##            
# 8 #             
# 9      S     ## 

[agent.0]
start = [5, 9]

[agent.1]
start = [5, 9]

[block.0.3]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.0.7]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.0.8]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.1.3]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.1.7]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.5.9]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.8.0]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 1

[block.10.1]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 1

[block.11.1]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.11.5]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.11.9]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.12.1]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.12.5]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0

[block.12.9]
type = "basic_block"
tags.passable = true
tags.slide = "fast"
tags.num_goal_agents = 0
