x_size = 6
y_size = 6
num_agents = 2
num_agents_must_finish = 2

[victory_conditions]
BlocksSatisfied = 1

[agent.0]
start = [4, 0]

[agent.1]
start = [4, 4]

[block.0.1]
type = "basic_block"

[block.2.2]
type = "basic_block"
tags.num_goal_agents = 2

[block.3.1]
type = "basic_block"

[block.4.0]
type = "basic_block"

[block.4.4]
type = "basic_block"
